// <auto-generated />
using System;
using Everis.Teste.Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Everis.Teste.Infrastructure.Migrations
{
    [DbContext(typeof(EverisContext))]
    partial class EverisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Everis.Teste.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPedido")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnName("dataPedido");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(128);

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnName("nomeCliente")
                        .HasMaxLength(128);

                    b.Property<double>("ValorTotal")
                        .HasColumnName("valorTotal");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
